### ISSUE TITLE
Support for Java 8?

### ISSUE THREAD

**Issue by carlocorradini** [cdimascio/dotenv-java#13]
I have a little request: **Can this awesome library add Java 8 as minimum version?**
Unfortunately I want to use the library in a project that is using Java 8.
Can this be achieved?
Thanks in advance

**Comment by cdimascio** [comment]
Yes. I’ll get that done tonight or tomorrow night

**Comment by carlocorradini** [comment]
> Yes. I’ll get that done tonight or tomorrow night

Thanks!!! 🎊🎊🎊

**Comment by cdimascio** [comment]
@carlocorradini java 8 is supported in `v2.1.x`
