### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by pysoftware** [cdimascio/dotenv-java#21]
java.lang.NoClassDefFoundError: io/github/cdimascio/dotenv/Dotenv

`
public final class PostgreDbConfig {

    private final String dbUri;
    private final String dbUser;
    private final String dbPassword;
    private final String dbDriver;

    private static PostgreDbConfig instance;

    public static PostgreDbConfig getInstance() {
        if (Objects.isNull(instance)) {
            instance = new PostgreDbConfig();
            return instance;
        }
        return instance;
    }

    @SneakyThrows
    private PostgreDbConfig() {
        Dotenv dotenv = Dotenv.configure()
                .directory(PostgreDbConfig.class.getResource("/.env").getPath())
                .load();
        dbUser = dotenv.get("db.uri");
        dbPassword = dotenv.get("db.user");
        dbUri = dotenv.get("db.password");
        dbDriver = dotenv.get("db.driver");

        try {
            Class.forName(dbDriver);
        } catch (ClassNotFoundException e) {
            throw new SQLException(dbDriver + " Driver is not found.");
        }
    }

    public Connection getConnection() throws SQLException {
        String url = "jdbc:postgresql://localhost/test";
        Properties props = new Properties();
        props.setProperty("user", "fred");
        props.setProperty("password", "secret");

        return DriverManager.getConnection(url, props);
    }
}
`

how to solve it?

**Comment by cdimascio** [comment]
have you added dotenv-java to your classpath?

have a look at this [example](https://github.com/cdimascio/dotenv-java/tree/master/examples/maven-simple). it provides a working example of basic project using maven
