### ISSUE TITLE
I'm curious...

### ISSUE THREAD

**Issue by nervo** [cdimascio/dotenv-java#24]
Imagine just 5 minutes that i would like to get around your strong advice to not use multiple dotenv files :)
Imagine just 5 minutes that i would like to have a `.env.dist` overriden by an optionnal `.env`
Just.. imagine...

How would i do ? 😘😘😘

**Comment by cdimascio** [comment]
@nervo you can get around this by using the `file()` method e.g.

```
String myDotenv = ".env.dist";
Dotenv dotenv = Dotenv.configure()
//    .directory("/assets") // optionally change the directory
    .filename(myDotenv);  // 
```

**Comment by nervo** [comment]
@cdimascio correct me if i'm wrong, but in the example you give, only the `.env.dist` file is loaded, no ?
