### ISSUE TITLE
Cannot resolve symbol 'github'

### ISSUE THREAD

**Issue by devpato** [cdimascio/dotenv-java#43]
I'm getting the following error when trying to use this dependency

> Cannot resolve symbol 'github'

I get the error above in this line of code:
**Java class**
`import io.github.cdimascio.dotenv.Dotenv;`

**pom.xml**

```
<dependency>
    <groupId>io.github.cdimascio</groupId>
    <artifactId>java-dotenv</artifactId>
    <version>5.2.2</version>
</dependency>
```

In my terminal I ran:

`mvn package`
`mvn dependency:resolve` 
`mvn clean install`

I'm new to Java and Maven and based on my small knowledge those commands above should help me install dependencies. Am I missing something?

**Comment by cdimascio** [comment]
Please use the latest dotenv-java

```
<dependency>
    <groupId>io.github.cdimascio</groupId>
    <artifactId>dotenv-java</artifactId>
    <version>2.3.2</version>
</dependency>
```
