### ISSUE TITLE
Question about the path

### ISSUE THREAD

**Issue by 1PV1** [cdimascio/dotenv-java#47]
Where do I need to create the .env file?
I tried in the following directories but I'm still getting `io.github.cdimascio.dotenv.DotenvException: Could not find /.env on the classpath`:
- life-plugin
- src
- main
- lifeplugin (the one with the java file)
![image](https://user-images.githubusercontent.com/98609931/224546917-39dfefe9-1764-4938-b7d2-3ec43b8f0d0d.png)

**Comment by cdimascio** [comment]
You can place it in resources
