### ISSUE TITLE
maven-plugin

### ISSUE THREAD

**Issue by bmarwell** [cdimascio/dotenv-java#53]
Hi!

I think a maven plugin would be nice.

```
<plugin>
  <artifactId>dotenv-maven-plugin</artifactId>
  <configuration>
    <dotEnvFile>${project.basedir}/.env</dotEnvFile>
  </configuration>
</plugin>
```

If you need help writing a maven plugin, let me know.

**Comment by cdimascio** [comment]
This is interesting. Feel free to take a stab at it. I would recommend an independent GitHub repo
