### ISSUE TITLE
[Enhancement request] write variable to env file

### ISSUE THREAD

**Issue by patpatpat123** [cdimascio/dotenv-java#58]
Hello there,

This is my first post in this repo. If not anything else, big thanks for this very cool project.

I would like to ask if it is possible to start a feature request.
As of right now, it is possible to "read" a env file by doing the ```dotenv.get("mykey")```

Would it be possible to have a feature to write some values?

For instance: starting with the file ```.env```

With content 

```
mykey = somevalue
```

Then to run ```dotenv.set("anotherkey", "someothervalue")```

And the ```.env``` file would be

```
anotherkey =someothervalue
```

Hope this is not too much of a trouble.

Thank you

**Comment by cdimascio** [comment]
This feature is out of scope for this lib. The lib is intended to load config rather than write it.
