### ISSUE TITLE
jimfs support

### ISSUE THREAD

**Issue by clintval** [cdimascio/dotenv-java#59]
For testing your library, I'd like to use an in-memory filesystem.

This should be possible but you are only testing for local files here:

https://github.com/cdimascio/dotenv-java/blob/5b6c71d213f05aa87be2655243d342ed888bbbc1/src/main/java/io/github/cdimascio/dotenv/internal/DotenvReader.java#L45

Are you interested in supporting in-memory test filesystems?

https://github.com/google/jimfs

**Comment by cdimascio** [comment]
This is interesting. PR is welcome
