### ISSUE TITLE
Version 3.0.1 released?

### ISSUE THREAD

**Issue by rivancic** [cdimascio/dotenv-java#64]
Maven central is saying there is a new hotfix version available 3.0.1

While I don't see it here in the releases. And I also can't find any commit in master or other branches that would hint to it.

Is this intentional?

![image](https://github.com/cdimascio/dotenv-java/assets/10011840/e0399bde-6ec5-437b-aca7-fddaf579f029)

https://mvnrepository.com/artifact/io.github.cdimascio/dotenv-java/3.0.1

**Comment by cdimascio** [comment]
thanks for the heads up. the hotfix details are now available in this repo
